version: "3.8"

services:
    vote:
        image: bretfisher/examplevotingapp_vote
        ports:
            - "80:80"
        networks:
            - front-end-network
        deploy:
            replicas: 2
    redis:
        image: redis:3.2
        networks:
            - front-end-network
    worker: 
        image: bretfisher/examplevotingapp_worker:java
        networks:
            - front-end-network
            - back-end-network
    db:
        image: postgres:9.4
        volumes:
            - "db-data:/var/lib/postgresql/data"
        networks:
            - back-end-network
        environment: 
            - POSTGRES_HOST_AUTH_METHOD=trust
    result:
        image: bretfisher/examplevotingapp_result
        networks:
            back-end-network
        ports:
            - "5001:80"

networks:
    back-end-network:
    front-end-network:

volumes:
    db-data:
